#!/bin/bash
exec /u/nlp/packages/scala/scala-2.11.0/bin/scala -cp /u/nlp/packages/qry/lib/qry.jar:$JAVANLP_HOME/projects/core/classes:$JAVANLP_HOME/projects/more/classes:$JAVANLP_HOME/projects/more/lib/typesafe-config-1.0.0.jar:$JAVANLP_HOME/projects/research/classes "$0" "$@"
!#
import Qry._  // Qry Core
import Stanford._  // Utilities for Stanford

using("./runDetails")
using("pbs")
pbs.name=nnqry311
pbs.queue=nlp

//using(getConfigOr(args, "/path/to/typesafe/config.conf"))  // tries to guess the config path from the command line arguments too

submit("/scr/nayakne/torch-install/bin/torch-lua /scr/nayakne/shiny-octo-lana-2/shiny-octo-lana/torch/figureOut/try1.lua")
